# Generated by Django 4.2.7 on 2025-01-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='project_name',
            field=models.CharField(blank=True, help_text='Optional. If not provided, will use folder name with timestamp.', max_length=255, null=True),
        ),
    ]
