# Generated by Django 4.2.7 on 2025-01-09 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_upload_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='retry_count',
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uploader.upload'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('info', 'Info')], max_length=10),
        ),
        migrations.AlterField(
            model_name='upload',
            name='project_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='status',
            field=models.CharField(default='submitted', max_length=50),
        ),
        migrations.DeleteModel(
            name='UploadFile',
        ),
    ]
