# Generated by Django 4.2.7 on 2025-01-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_remove_upload_retry_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='irida_project_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='sample_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='upload',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('uploading', 'Uploading'), ('failed', 'Failed'), ('success', 'Success')], default='submitted', max_length=50),
        ),
    ]
