# Generated by Django 4.2.7 on 2025-01-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0004_upload_irida_project_id_upload_sample_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='irida_run_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='uploaded_samples',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
