# Generated by Django 4.2.18 on 2025-01-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0005_upload_irida_run_id_upload_uploaded_samples'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
    ]
